baseURL = "https://letsreview.github.io/"
languageCode = "en-us"
title = "Let's Review"
theme = "hugo-PaperMod"

[menu]

  [[menu.main]]
    name = "About"
    url = "about/"

  [[menu.main]]
    name = "Groups"
    url = "groups/"

  [[menu.main]]
    name = "Posts"
    url = "posts/"

  [[menu.main]]
    name = "Resources"
    url = "resources/"

[params.homeInfoParams]
title = "Let's Review"
content = "Reviewing Open Source Software together."

[[params.socialIcons]]
name = "github"
url = "https://github.com/letsreview"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/LetsreviewCodes"
